<?php

namespace StageBundle\Repository;

/**
 * indexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class indexeRepository extends \Doctrine\ORM\EntityRepository
{
}
