<?php

namespace StageBundle\Repository;

/**
 * regleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class regleRepository extends \Doctrine\ORM\EntityRepository
{
}
