<?php

namespace StageBundle\Repository;

/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends \Doctrine\ORM\EntityRepository
{
}
